linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - forbidigo
    - gochecknoglobals
    - lll
    - wsl
    - nlreturn

linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  misspell:
    locale: US
