linters:
  enable-all: true
  disable:
    - deadcode
    - dupword
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - golint
    - ifshort
    - interfacer
    - lll
    - maligned
    - nlreturn
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - varnamelen
    - wsl

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
