linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - forbidigo
    - gochecknoglobals
    - lll
    - wsl
    - nlreturn
    - varnamelen

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
